### ISSUE TITLE
ErrorException: cURL error 7: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) src/XF/Error.php:77

### ISSUE THREAD

**Issue by TylerAustin7** [Xon/XenForo2-PasswordTools#2]
I am having some issues related to your add-ons some reason it’s having some conflict with the cURL 

#0 src/XF.php(219): XF\Error->logError('cURL error 7:  ...', false)
#1 src/addons/SV/PasswordTools/XF/Entity/UserAuth.php(224): XF::logError('cURL error 7:  ...')
#2 src/addons/SV/PasswordTools/XF/Entity/UserAuth.php(147): SV\PasswordTools\XF\Entity\UserAuth->getPwnedPrefixMatches('DD54A', 1654138124, false)
#3 src/addons/SV/PasswordTools/XF/Service/User/Login.php(37): SV\PasswordTools\XF\Entity\UserAuth->isPwnedPassword('*****', 0, false)
#4 src/XF.php(377): SV\PasswordTools\XF\Service\User\Login->SV\PasswordTools\XF\Service\User\{closure}()
#5 src/XF/Mvc/Dispatcher.php(158): XF::triggerRunOnce(true)
#6 src/XF/Mvc/Dispatcher.php(57): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#7 src/XF/App.php(2352): XF\Mvc\Dispatcher->run()
#8 src/XF.php(524): XF\App->run()
#9 admin.php(13): XF::runApp('XF\\Admin\\App')
#10 {main}
Request state
array(4) {
  ["url"] => string(22) "/admin.php?login/login"
  ["referrer"] => string(30) "https://xen-shop.com/admin.php"
  ["_GET"] => array(1) {
    ["login/login"] => string(0) ""
  }
  ["_POST"] => array(6) {
    ["_xfToken"] => string(8) "********"
    ["login"] => string(6) "NICK97"
    ["password"] => string(8) "********"
    ["_xfRequestUri"] => string(10) "/admin.php"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }

I do known I have this no problem before installing this add-ons and once I install the add-ons the error to be shown up in my error log. Also I can confirmed there is no issue related to my server at this time and it’s just your add-on is having some problems 
![2B9E52AD-83BF-48A8-9257-B1FAEA80D45E](https://user-images.githubusercontent.com/40327737/172754488-a84975eb-52a2-4bce-9b0f-e6d349058267.png)

**Comment by TylerAustin7** [comment]
Also this issue have been since v3.6.4 from your add-on 

One more thing why are you using outdated upstream Sources for your add-ons?

**Comment by Xon** [comment]
This is related to a server configuration issue, as this code uses curl to make outbound HTTPS API calls.

For actual add-on support, you should post in the add-on's support thread on the official xenforo forums or my add-on site. Both will require a valid xenforo licence.

**Comment by TylerAustin7** [comment]
As I did told you my server is working properly as you said as this code uses curl to make outbound HTTPS API calls. can you please confirm to see if this a problem related to the outbound HTTPS API calls?
