### ISSUE TITLE
Installation failed. 

### ISSUE THREAD

**Issue by Code-Egg** [Xon/XenForo2-PasswordTools#4]
Hi,
Thanks for the tool, I tried to install the password tool here src/addons/SV/PasswordTools, but it returns a 500 error when I click the install from the browser. 
Here's the server error log, 
```
STDERR] PHP Fatal error:  Trait 'SV\StandardLib\InstallerHelper' not found in /xxx/xxx/public_html/src/addons/SV/PasswordTools/Setup.php on line 17
```
Is there anything I can do to fix it? The current xenforo version is v2.0.x, could that be the problem?

**Comment by Xon** [comment]
This add-on requires XF v2.1.0+, there is probably an older enough version which still supports XF2.0 but it would require digging through release notes to find it

The installer would have told you that this add-on depends on my [SV\StandardLib add-on](https://github.com/Xon/XenForo2-StandardLib).

 Support is generally only provided on xenforo.com's community forums for known valid XF customers.
